# name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

variables:
 - group: terraformvars
  
# Only run against develop
trigger: none

pool: 
  vmImage: 'ubuntu-latest'

# Don't run against PRs
# pr: none

stages :
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: Bash@3
        displayName: Terraform Init
        env:            
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)              
         ARM_TENANT_ID: $(ARM_TENANT_ID)
        inputs:
          #workingDirectory: '$(System.DefaultWorkingDirectory)/cfg/'          
          #targetType: 'inline'
          script: |
            terraform init
            
  
      - task: Bash@3
        displayName: Terraform Apply
        env:            
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)              
         ARM_TENANT_ID: $(ARM_TENANT_ID)
        inputs:      
          #workingDirectory: '$(System.DefaultWorkingDirectory)/cfg/'   
          #targetType: 'inline'
          script: |
            terraform apply -auto-approve
